### ISSUE TITLE
Can not know which block is focused

### ISSUE THREAD

**Issue by pythops** [Zatfer17/tui-network#4]
Maybe make the borders of focused block bold and the others just normal borders

**Comment by Zatfer17** [comment]
Thanks for the inputs @pythops ! I'll look into them during Christmas days. Did you try it btw? Ideally I'd like to make a couple more essential system tuis (date-time, power and sound settings) and then wrap them in a tui settings "dashboard"

**Comment by pythops** [comment]
>  Did you try it btw ?

Yep I tried it and that's how I noticed the focus block

>  I'd like to make a couple more essential system tuis (date-time, power and sound settings) 

Go for it :rocket: , we need more TUIs

**Comment by Zatfer17** [comment]
Fixed
